export { default as PHome } from './PHome'
export { default as PLogin } from './PLogin'
export { default as PGame } from './PGame'
export { default as PGameChronology } from './PGameChronology'
export { default as PLeaderboard } from './PLeaderboard'
export { default as PPastGames } from './PPastGames'
